on: [push, pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
        # Checkout this repo
      - name: Checkout
        uses: actions/checkout@v2
        # Checkout the private repo containing the action to run
      - name: Checkout private action repo
        uses: actions/checkout@v2
        with:
          repository: rennemannd/pr-test
          ref: v1.0
          token: ${{ secrets.GIT_HUB_TOKEN }}
          path: fuggma
      - name: Hello world action step
        id: hello
        uses: ./fuggma/.github/actions
        with:
          who-to-greet: 'South Dakota'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
