on:
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'
    types: [opened, edited, synchronized, reopened]
  repository_dispatch:
    types: [updated]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Checking PR Request
    steps:
      # To use this repository's private action, first checkout repo...
      - name: Checkout
        uses: actions/checkout@v2
 
      # ... then checkout the private repo containing the action to run
      - name: Checkout private action repo
        uses: actions/checkout@v2
        with:
          repository: infotechfl/ap-workflow-bot
          ref: master
          token: ${{ secrets.BOT_PAT }}
          path: temp

      - name: Checking Request
        uses: ./temp/.github/actions/action-1
        if: github.event_name == 'pull_request'
        id: TestFormatting
        with:
          key: putPRinfohere
